name: tigramite4_conda
dependencies:
    - python=3
    - numpy>=1.14.0
    - scipy>=1.3.0
    - scikit-learn>=0.21.2
    - matplotlib>=3.1.1
    - networkx>=2.4
    - cython>=0.26
    - torch>=1.7
    - gpytorch>=1.4
    - dcor>=0.5.3